# Generated by Django 3.1 on 2024-09-16 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_eventpage_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='eventdate',
            field=models.DateField(default=datetime.date(2024, 9, 16)),
        ),
    ]
